// This file has been autogenerated. To re-generate, build the Server project.
export interface IServiceDto {
    ValidUntilUtc: string;
}
export interface IHttpingDto extends IServiceDto {
    Targets: ({    Daily: ({    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;})[] | null;    Hourly: ({    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;})[] | null;    Last24h: {    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;};    Last30d: {    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;};    Last30m: {    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;};    Monthly: ({    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;})[] | null;    Name: string | null;    Recent: (number)[] | null;    Twominutely: ({    ErrorCount: number;    MsResponsePrc01: number;    MsResponsePrc25: number;    MsResponsePrc50: number;    MsResponsePrc75: number;    MsResponsePrc95: number;    MsResponsePrc99: number;    TimeoutCount: number;    TotalCount: number;})[] | null;} | null)[] | null;
    ValidUntilUtc: string;
}
export interface IPingDto extends IServiceDto {
    Last: number | null;
    Recent: (number | null)[] | null;
    ValidUntilUtc: string;
}
export interface IReloadDto extends IServiceDto {
    StaticFilesHash: string | null;
    ValidUntilUtc: string;
}
export interface IRouterDto extends IServiceDto {
    HistoryHourly: ({    RxRate: number;    TxRate: number;} | null)[] | null;
    HistoryRecent: ({    RxRate: number;    TxRate: number;} | null)[] | null;
    RxAverageRecent: number;
    RxLast: number;
    TxAverageRecent: number;
    TxLast: number;
    ValidUntilUtc: string;
}
export interface ITimeDto extends IServiceDto {
    LocalOffsetHours: number;
    TimeZones: ({    DisplayName: string | null;    OffsetHours: number;} | null)[] | null;
    ValidUntilUtc: string;
}
export interface IWeatherDto extends IServiceDto {
    CurTemperature: number;
    CurTemperatureColor: string | null;
    MaxTemperature: number;
    MaxTemperatureAtDay: string | null;
    MaxTemperatureAtTime: string | null;
    MaxTemperatureColor: string | null;
    MinTemperature: number;
    MinTemperatureAtDay: string | null;
    MinTemperatureAtTime: string | null;
    MinTemperatureColor: string | null;
    SolarNoonTime: string | null;
    SunriseTime: string | null;
    SunsetDeltaTime: string | null;
    SunsetTime: string | null;
    ValidUntilUtc: string;
}
