// This file has been autogenerated. To re-generate, build the Server project.
export interface IPingDto {
    Last: number | null;
    Recent: (number | null)[] | null;
    ValidUntilUtc: string;
}
export interface IReloadDto {
    StaticFilesHash: string | null;
    ValidUntilUtc: string;
}
export interface IRouterDto {
    RxAverageRecent: number;
    RxLast: number;
    TxAverageRecent: number;
    TxLast: number;
    ValidUntilUtc: string;
}
export interface IWeatherDto {
    CurTemperature: number;
    MaxTemperature: number;
    MaxTemperatureAtDay: string | null;
    MaxTemperatureAtTime: string | null;
    MinTemperature: number;
    MinTemperatureAtDay: string | null;
    MinTemperatureAtTime: string | null;
    SolarNoonTime: string | null;
    SunriseTime: string | null;
    SunsetDeltaTime: string | null;
    SunsetTime: string | null;
    ValidUntilUtc: string;
}
