// This file has been autogenerated. To re-generate, build the Server project.
export interface IServiceDto {
    ValidUntilUtc: string;
}
export interface IPingDto extends IServiceDto {
    Last: number | null;
    Recent: (number | null)[] | null;
    ValidUntilUtc: string;
}
export interface IReloadDto extends IServiceDto {
    StaticFilesHash: string | null;
    ValidUntilUtc: string;
}
export interface IRouterDto extends IServiceDto {
    HistoryHourly: ({    RxRate: number;    TxRate: number;} | null)[] | null;
    HistoryRecent: ({    RxRate: number;    TxRate: number;} | null)[] | null;
    RxAverageRecent: number;
    RxLast: number;
    TxAverageRecent: number;
    TxLast: number;
    ValidUntilUtc: string;
}
export interface ITimeDto extends IServiceDto {
    LocalOffsetHours: number;
    TimeZones: ({    DisplayName: string | null;    OffsetHours: number;} | null)[] | null;
    ValidUntilUtc: string;
}
export interface IWeatherDto extends IServiceDto {
    CurTemperature: number;
    MaxTemperature: number;
    MaxTemperatureAtDay: string | null;
    MaxTemperatureAtTime: string | null;
    MinTemperature: number;
    MinTemperatureAtDay: string | null;
    MinTemperatureAtTime: string | null;
    SolarNoonTime: string | null;
    SunriseTime: string | null;
    SunsetDeltaTime: string | null;
    SunsetTime: string | null;
    ValidUntilUtc: string;
}
