using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using RT.Util.ExtensionMethods;

namespace StatusScreenSite
{
    interface IServiceDto
    {
        DateTime ValidUntilUtc { get; }
    }

    static class TypescriptDto
    {
        public static void GenerateTypescriptFile(string filename)
        {
            var file = new StringBuilder();
            file.AppendLine("// This file has been autogenerated. To re-generate, build the Server project.");
            file.Append($"export interface {nameof(IServiceDto)} ");
            outputObject(file, typeof(IServiceDto), multiline: true);
            foreach (var type in Assembly.GetEntryAssembly().GetTypes().Where(t => t.GetInterfaces().Contains(typeof(IServiceDto))).OrderBy(t => t.Name))
            {
                file.Append($"export interface I{type.Name} extends {nameof(IServiceDto)} ");
                outputObject(file, type, multiline: true);
            }

            filename = Path.GetFullPath(filename);
            Console.WriteLine($"Saving DTOs to {filename}...");
            Directory.CreateDirectory(Path.GetDirectoryName(filename));
            File.WriteAllText(filename, file.ToString());
        }

        private static void outputObject(StringBuilder file, Type type, bool multiline)
        {
            file.Append($"{{");
            if (multiline) file.AppendLine();
            foreach (var prop in type.GetProperties().OrderBy(p => p.Name))
            {
                file.Append($"    {prop.Name}: ");
                var propType = prop.PropertyType;
                outputType(file, propType);
                file.Append(";");
                if (multiline) file.AppendLine();
            }
            file.Append($"}}");
            if (multiline) file.AppendLine();
        }

        private static void outputType(StringBuilder file, Type propType)
        {
            bool nullable = !propType.IsValueType;
            if (propType.IsGenericType && propType.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                nullable = true;
                propType = propType.GetGenericArguments()[0];
            }
            if (propType == typeof(string))
                file.Append("string");
            else if (propType == typeof(int) || propType == typeof(double) || propType == typeof(decimal))
                file.Append("number");
            else if (propType == typeof(DateTime))
                file.Append("string");
            else if (propType.IsArray)
            {
                file.Append("(");
                outputType(file, propType.GetElementType());
                file.Append(")[]");
            }
            else
            {
                outputObject(file, propType, multiline: false);
            }

            if (nullable)
                file.Append(" | null");
        }
    }
}
